# -*- mode: python ; coding: utf-8 -*-
from PyInstaller.utils.hooks import collect_all
import os
import sys

# Add current directory to sys.path to ensure root modules are found
current_dir = os.path.dirname(os.path.abspath(SPEC))
if current_dir not in sys.path:
    sys.path.insert(0, current_dir)

exe_name = 'gluesync-automator-windows.exe'

def _load_automator_version():
    version_path = os.path.join(current_dir, 'automator_app', 'VERSION')
    if not os.path.isfile(version_path):
        raise SystemExit(f'Missing {version_path}')
    with open(version_path, encoding='utf-8-sig') as handle:
        for line in handle:
            version = line.strip()
            if version:
                return version
    raise SystemExit(f'{version_path} is empty')


def _file_version_tuple(version):
    import re
    match = re.match(r'^(\d+)\.(\d+)\.(\d+)(?:\.(\d+))?', version)
    if not match:
        raise SystemExit(f'Automator version {version!r} has no numeric prefix')
    return tuple(int(match.group(i) or 0) for i in range(1, 5))


def _write_windows_version_info(version):
    filevers = _file_version_tuple(version)
    # PyInstaller execs this file. Regenerated on every Windows build from automator_app/VERSION.
    body = f"""# Generated by automator-windows.spec from automator_app/VERSION. Do not edit by hand.
# UTF-8
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={filevers},
    prodvers={filevers},
    mask=0x3f,
    flags=0x0,
    OS=0x4,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo(
      [
        StringTable(
          u'040904B0',
          [
            StringStruct(u'CompanyName', u'MOLO17'),
            StringStruct(u'ProductName', u'Gluesync Automator'),
            StringStruct(u'ProductVersion', u'{version}'),
            StringStruct(u'FileDescription', u'Gluesync Automator for Windows'),
            StringStruct(u'FileVersion', u'{version}'),
            StringStruct(u'InternalName', u'gluesync-automator'),
            StringStruct(u'LegalCopyright', u'Copyright (C) 2025 MOLO17. All rights reserved.'),
            StringStruct(u'OriginalFilename', u'gluesync-automator-windows.exe'),
          ]
        )
      ]
    ),
    VarFileInfo([VarStruct(u'Translation', [1033, 1200])])
  ]
)
"""
    path = os.path.join(current_dir, 'windows-version-info.py')
    with open(path, 'w', encoding='utf-8', newline='\n') as handle:
        handle.write(body)
    return path


_windows_version_info = _write_windows_version_info(_load_automator_version())
runtime_tmpdir = 'C:\\Windows\\Temp'

datas = [
    ('automator_app\\static', 'static'),
    ('automator_app\\VERSION', 'automator_app'),
    ('agents.json', '.'),
]
binaries = []
hiddenimports = [
    'create_user_defined_functions',
    'create_all_tables',
    'create_all_entities',
    'commons',
    'utils.log',
    'utils.core_hub_client',
    'utils.chronos_client',
    'utils.gluesync_sdk_client',
    'automator_app.app',
    'automator_app.cli',
    'automator_app.corehub',
    'automator_app.state',
    'automator_app.version',
]


a = Analysis(
    ['run_automator.py'],
    pathex=['.'],
    binaries=binaries,
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name=exe_name,
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=runtime_tmpdir,
    console=True,
    disable_windowed_traceback=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='automator_app\\static\\favicon.ico',
    version=_windows_version_info,
)
