import java.util.Map;
import kotlin.Pair;
import com.molo17.gluesync.commons.model.api.MappingFunctionOperation;
import org.slf4j.Logger;
import java.lang.String;
import java.math.BigDecimal;
import java.time.LocalTime;
import java.time.LocalDate;
import java.time.LocalDateTime;

/*
 * That's a Gluesync UDF
 * Generated by generate_udf_import_package.py on 2026-06-10 14:23:32
 * Entity: KBM400MFG.FLVNDHST (DbMoto ReplicationID: 274)
 *
 * Decoded DbMoto field-mapping expressions:
 *   VHDTCV <- MakeDateTime([VHDTCV])
 *   VHDTRJ <- MakeDateTime([VHDTRJ])
 *   VHDTRT <- MakeDateTime([VHDTRT])
 *   VHDTRW <- MakeDateTime([VHDTRW])
 *   VHDTSC <- MakeDateTime([VHDTSC])
 *   VHDTSK <- MakeDateTime([VHDTSK])
 *   VHDTSP <- MakeDateTime([VHDTSP])
 *
 * The function is invoked by Gluesync whatever the operation is (INSERT, UPDATE, DELETE),
 * as well as while performing the Snapshot task, and must return a Pair of the
 * (possibly changed) operation and the new values for the target row.
 */
public class UDF_KBM400MFG_FLVNDHST {

    public Pair<MappingFunctionOperation, Map<String, Object>> onChange(Map<String, Object> newValues, Map<String, Object> oldValues, MappingFunctionOperation operation, Logger logger) {
        // Source columns: VHACN, VHAPVN, VHCNTD, VHCO, VHCRCV, VHCRTC, VHCSCH, VHDRCV, VHDREJ, VHDRET, VHDRWK, VHDSCH, VHDSCP, VHDSTK, VHDTCV, VHDTRJ, VHDTRT, VHDTRW, VHDTSC, VHDTSK, VHDTSP, VHEDAY, VHETYP, VHGLRF, VHIMCS, VHINVN, VHLOT, VHMRCV, VHMREJ, VHMRET, VHMRWK, VHMSCH, VHMSCP, VHMSTK, VHNO, VHORWK, VHOSLC, VHPDFG, VHPN, VHPOCS, VHPOLN, VHPON, VHPOUM, VHPQTY, VHPROJ, VHPSTK, VHQRCV, VHQREJ, VHQRET, VHQRWK, VHQSCH, VHQSCP, VHQSRA, VHQSTK, VHQTY1, VHQTY2, VHQTY3, VHRDTY, VHREJN, VHRPDT, VHSCND, VHSVIA, VHTRWK, VHVDPN, VHVEND, VHVNDC, VHVNDL, VHVRNO, VHWHSE, VHWRCN, VHYRCV, VHYREJ, VHYRET, VHYRWK, VHYSCH, VHYSCP, VHYSTK, VHDFECTCDE, VHNONCONF
        // Target columns: VHACN, VHAPVN, VHCNTD, VHCO, VHCRTC, VHDTCV, VHDTRJ, VHDTRT, VHDTRW, VHDTSC, VHDTSK, VHDTSP, VHEDAY, VHETYP, VHGLRF, VHIMCS, VHINVN, VHLOT, VHNO, VHORWK, VHOSLC, VHPDFG, VHPN, VHPOCS, VHPOLN, VHPON, VHPOUM, VHPQTY, VHPROJ, VHPSTK, VHQRCV, VHQREJ, VHQRET, VHQRWK, VHQSCH, VHQSCP, VHQSRA, VHQSTK, VHQTY1, VHQTY2, VHQTY3, VHRDTY, VHREJN, VHRPDT, VHSCND, VHSVIA, VHTRWK, VHVDPN, VHVEND, VHVNDC, VHVNDL, VHVRNO, VHWHSE, VHWRCN, VHDFECTCDE, VHNONCONF

        Map<String, Object> modified_values = newValues;

        if (operation == MappingFunctionOperation.Delete) {
            modified_values.put("VHDTCV", null);
            modified_values.put("VHDTRJ", null);
            modified_values.put("VHDTRT", null);
            modified_values.put("VHDTRW", null);
            modified_values.put("VHDTSC", null);
            modified_values.put("VHDTSK", null);
            modified_values.put("VHDTSP", null);
            return new Pair<>(operation, modified_values);
        }

        try {
                modified_values.put("VHDTCV", makeDateTime(toLocalDate(newValues.get("VHDTCV"))));
                modified_values.put("VHDTRJ", makeDateTime(toLocalDate(newValues.get("VHDTRJ"))));
                modified_values.put("VHDTRT", makeDateTime(toLocalDate(newValues.get("VHDTRT"))));
                modified_values.put("VHDTRW", makeDateTime(toLocalDate(newValues.get("VHDTRW"))));
                modified_values.put("VHDTSC", makeDateTime(toLocalDate(newValues.get("VHDTSC"))));
                modified_values.put("VHDTSK", makeDateTime(toLocalDate(newValues.get("VHDTSK"))));
                modified_values.put("VHDTSP", makeDateTime(toLocalDate(newValues.get("VHDTSP"))));
        } catch (Exception e) {
            throw new RuntimeException(e);
        }

        return new Pair<>(operation, modified_values);
    }

    /* ------------------------------------------------------------------
     * Helper functions ported from the DbMoto VB.NET scripting library.
     * Generated from the Gluesync UDF master template.
     * ------------------------------------------------------------------ */

    public static BigDecimal toBigDecimal(Object value) {
        if (value == null) {
            return null;
        }
        if (value instanceof BigDecimal) {
            return (BigDecimal) value;
        }
        return new BigDecimal(value.toString());
    }

    public static LocalDate toLocalDate(Object value) {
        if (value == null) {
            return null;
        }
        if (value instanceof LocalDate) {
            return (LocalDate) value;
        }
        if (value instanceof LocalDateTime) {
            return ((LocalDateTime) value).toLocalDate();
        }
        String s = value.toString().trim();
        if (s.isEmpty()) {
            return null;
        }
        if (s.length() >= 10) {
            return LocalDate.parse(s.substring(0, 10));
        }
        return LocalDate.parse(s);
    }

    public static LocalTime toLocalTime(Object value) {
        if (value == null) {
            return null;
        }
        if (value instanceof LocalTime) {
            return (LocalTime) value;
        }
        if (value instanceof LocalDateTime) {
            return ((LocalDateTime) value).toLocalTime();
        }
        String s = value.toString().trim();
        if (s.isEmpty()) {
            return null;
        }
        int tIdx = s.indexOf('T');
        if (tIdx >= 0) {
            s = s.substring(tIdx + 1);
        }
        if (s.length() > 8) {
            s = s.substring(0, 8);
        }
        return LocalTime.parse(s);
    }

    public static String toUpperString(Object value) {
        return value == null ? null : value.toString().toUpperCase();
    }

    public static String toLowerString(Object value) {
        return value == null ? null : value.toString().toLowerCase();
    }

    public static String trimString(Object value) {
        return value == null ? null : value.toString().trim();
    }

    /* DbMoto Int(x / y): integral part of the division */
    public static BigDecimal intDivide(BigDecimal value, BigDecimal divisor) {
        if (value == null || divisor == null) {
            return null;
        }
        return value.divideToIntegralValue(divisor);
    }

    /* DbMoto Int(x): truncates the decimal part */
    public static BigDecimal truncateToInt(BigDecimal value) {
        if (value == null) {
            return null;
        }
        return new BigDecimal(value.toBigInteger());
    }

    /* DbMoto LowDate(x): nulls out dates below the SQL Server low boundary */
    public static Object lowDate(Object value) {
        if (value == null) {
            return null;
        }
        LocalDate d = null;
        if (value instanceof LocalDateTime) {
            d = ((LocalDateTime) value).toLocalDate();
        } else if (value instanceof LocalDate) {
            d = (LocalDate) value;
        }
        if (d != null && d.compareTo(LocalDate.parse("1753-01-01")) < 0) {
            return null;
        }
        return value;
    }

    /* Decimal date in MMDDYY format -> DateTime */
    public static Object getDateMMDDYY(BigDecimal fullDate) throws Exception {
        if (fullDate == null) {
            return null;
        }
        int divDate = fullDate.abs().intValue();
        int day = (divDate % 10000) / 100;
        int month = divDate / 10000;
        int year = divDate % 100;
        if (year < 40) {
            year = 2000 + year;
        } else {
            year = 1900 + year;
        }
        return makeDateTime("YYYY", new BigDecimal(month), new BigDecimal(day), new BigDecimal(year));
    }

    /* Decimal date in CYYMMDD format -> DateTime */
    public static Object getDateCYYMMDD(BigDecimal fullDate) throws Exception {
        if (fullDate == null) {
            return null;
        }
        int divDate = fullDate.abs().intValue();
        int month = (divDate % 10000) / 100;
        int day = divDate % 100;
        int year;
        int century = divDate / 1000000;
        switch (century) {
            case 0:
                year = 1900 + (divDate / 10000);
                break;
            case 1:
                year = 2000 + ((divDate / 10000) - 100);
                break;
            default:
                return null;
        }
        return makeDateTime("YYYY", new BigDecimal(month), new BigDecimal(day), new BigDecimal(year));
    }

    /* Decimal date in YYMMDD format -> DateTime */
    public static Object getDateYYMMDD(BigDecimal fullDate) throws Exception {
        if (fullDate == null) {
            return null;
        }
        int divDate = fullDate.abs().intValue();
        int month = (divDate % 10000) / 100;
        int day = divDate % 100;
        int year = divDate / 10000;
        if (year < 40) {
            year = 2000 + year;
        } else {
            year = 1900 + year;
        }
        return makeDateTime("YYYY", new BigDecimal(month), new BigDecimal(day), new BigDecimal(year));
    }

    /* Decimal date in YYYYMMDD format -> DateTime */
    public static Object getDateYYYYMMDD(BigDecimal fullDate) throws Exception {
        if (fullDate == null) {
            return null;
        }
        int divDate = fullDate.abs().intValue();
        int month = (divDate % 10000) / 100;
        int day = divDate % 100;
        int year = divDate / 10000;
        return makeDateTime("YYYY", new BigDecimal(month), new BigDecimal(day), new BigDecimal(year));
    }

    /* MakeDateTime(formatYear, month, day, year) */
    public static Object makeDateTime(String formatYear, BigDecimal month, BigDecimal day, BigDecimal year) throws Exception {
        if (month == null || day == null || year == null) {
            return null;
        }
        int fullYear;
        int intMonth = month.intValue();
        int intDay = day.intValue();
        int intYear = year.intValue();

        if ("YY".equals(formatYear.toUpperCase())) {
            if (intYear <= 39) {
                fullYear = 2000 + intYear;
            } else {
                fullYear = 1900 + intYear;
            }
        } else if ("YYYY".equals(formatYear.toUpperCase())) {
            fullYear = intYear;
        } else {
            throw new Exception("Valid year formats are YY or YYYY");
        }

        if ((intMonth < 1) || (intMonth > 12)) {
            return null;
        }
        if ((intDay < 1) || (intDay > 31)) {
            return null;
        }
        if (fullYear < 1753) {
            return null;
        }
        if (((intMonth == 4) || (intMonth == 6) || (intMonth == 9) || (intMonth == 11)) && (intDay > 30)) {
            return null;
        } else if (intMonth == 2) {
            if ((fullYear % 4) == 0) {
                if (intDay > 29) {
                    return null;
                }
            } else {
                if (intDay > 28) {
                    return null;
                }
            }
        }
        return LocalDate.of(fullYear, intMonth, intDay);
    }

    /* MakeDateTime(month, day, shortYear, century) */
    public static Object makeDateTime(BigDecimal month, BigDecimal day, BigDecimal shortYear, BigDecimal century) throws Exception {
        if (month == null || day == null || shortYear == null || century == null) {
            return null;
        }
        BigDecimal fullYear;
        int intCentury = century.intValue();
        int intShortYear = shortYear.intValue();
        if (intCentury < 19) {
            fullYear = new BigDecimal(1900 + (100 * intCentury) + intShortYear);
        } else {
            fullYear = new BigDecimal((100 * intCentury) + intShortYear);
        }
        return makeDateTime("YYYY", month, day, fullYear);
    }

    /* MakeDateTime(formatDate, fullDate, century) */
    public static Object makeDateTime(String formatDate, BigDecimal fullDate, BigDecimal century) throws Exception {
        if (fullDate == null || century == null) {
            return null;
        }
        int divDate = fullDate.intValue();
        int day;
        int month;
        int year;
        int fullYear;
        int intCentury = century.intValue();

        if ("MMDDYY".equals(formatDate.toUpperCase())) {
            month = divDate / 10000;
            day = (divDate % 10000) / 100;
            year = divDate % 100;
        } else {
            throw new Exception("Valid format is MMDDYY");
        }

        if (intCentury < 19) {
            fullYear = 1900 + (100 * intCentury) + year;
        } else {
            fullYear = (100 * intCentury) + year;
        }
        return makeDateTime("YYYY", new BigDecimal(month), new BigDecimal(day), new BigDecimal(fullYear));
    }

    /* MakeDateTime(formatDate, fullDate) */
    public static Object makeDateTime(String formatDate, BigDecimal fullDate) throws Exception {
        if (fullDate == null) {
            return null;
        }
        switch (formatDate.toUpperCase()) {
            case "CYYMMDD":
                return getDateCYYMMDD(fullDate);
            case "MMDDYY":
                return getDateMMDDYY(fullDate);
            case "YYMMDD":
                return getDateYYMMDD(fullDate);
            case "YYYYMMDD":
                return getDateYYYYMMDD(fullDate);
            default:
                throw new Exception("Valid formats are CYYMMDD, MMDDYY, YYMMDD, and YYYYMMDD.");
        }
    }

    /* MakeDateTime(fullDate) - DATE passthrough with low-boundary validation */
    public static Object makeDateTime(LocalDate fullDate) {
        if (fullDate == null) {
            return fullDate;
        }
        if (fullDate.compareTo(LocalDate.parse("1753-01-01")) < 0) {
            return null;
        }
        return fullDate;
    }

    /* MakeDateTime(fullDate, fullTime) - DATE + TIME combination */
    public static Object makeDateTime(LocalDate fullDate, LocalTime fullTime) {
        if (fullDate == null) {
            return fullDate;
        }
        if (fullDate.compareTo(LocalDate.parse("1753-01-01")) < 0) {
            return null;
        }
        if (fullTime == null) {
            return fullDate;
        }
        return LocalDateTime.of(fullDate, fullTime);
    }

    /* MakeDateTime(fullDate, decimalTime) - DATE + decimal HHMMSS combination */
    public static Object makeDateTime(LocalDate fullDate, BigDecimal fullTime) {
        if (fullDate == null) {
            return fullDate;
        }
        if (fullDate.compareTo(LocalDate.parse("1753-01-01")) < 0) {
            return null;
        }
        if (fullTime == null) {
            return fullDate;
        }
        int tempTime = fullTime.abs().intValue();
        int hours = tempTime / 10000;
        int minutes = (tempTime % 10000) / 100;
        int seconds = tempTime % 100;
        if ((hours > 23) || (minutes > 59) || (seconds > 59)) {
            return fullDate;
        }
        return LocalDateTime.of(fullDate, LocalTime.of(hours, minutes, seconds));
    }

}
