import java.util.Map;
import kotlin.Pair;
import com.molo17.gluesync.commons.model.api.MappingFunctionOperation;
import org.slf4j.Logger;
import java.lang.String;
import java.math.BigDecimal;
import java.time.LocalTime;
import java.time.LocalDate;
import java.time.LocalDateTime;

/*
 * That's a Gluesync UDF
 * Generated by generate_udf_import_package.py on 2026-06-19 16:50:37
 * Entity: KBM400MFG.FMWOSUM (DbMoto ReplicationID: 278)
 *
 * Decoded DbMoto field-mapping expressions:
 *   WOCDATE <- MakeDateTime([WOCMM],[WOCDD],[WOCYY],[WOCCC])
 *   WODLDATE <- MakeDateTime("MMDDYY",[WODLSA],[WODLCC])
 *   WODTCLDT <- MakeDateTime("MMDDYY",[WODTCL])
 *   WODTCMDT <- MakeDateTime("MMDDYY",[WODTCM])
 *   WODTLRDT <- MakeDateTime("MMDDYY",[WODTLR])
 *   WODTORDT <- MakeDateTime("MMDDYY",[WODTOR])
 *   WODTSTDT <- MakeDateTime("MMDDYY",[WODTST])
 *   WOMCTGDATE <- MakeDateTime(MakeDateTime("MMDDYY",[WOMCDG]),[WOMCTG])
 *   WOMCTRDATE <- MakeDateTime(MakeDateTime("MMDDYY",[WOMCDR]), [WOMCTR])
 *   WOMPDGDATE <- MakeDateTime(MakeDateTime("MMDDYY",[WOMPDG]),[WOMPTG])
 *   WOMPDRDATE <- MakeDateTime(MakeDateTime("MMDDYY",[WOMPDR]), [WOMPTR])
 *   WOODUE <- MakeDateTime("MMDDYY",[WOODUE])
 *   WOUDATE <- MakeDateTime(  MakeDateTime( "YYYYMMDD",[WOUDTE] )  , [WOUTIM] )
 *
 * The function is invoked by Gluesync whatever the operation is (INSERT, UPDATE, DELETE),
 * as well as while performing the Snapshot task, and must return a Pair of the
 * (possibly changed) operation and the new values for the target row.
 */
public class UDF_KBM400MFG_FMWOSUM {

    public Pair<MappingFunctionOperation, Map<String, Object>> onChange(Map<String, Object> newValues, Map<String, Object> oldValues, MappingFunctionOperation operation, Logger logger) {
        // Source columns: WOACD, WOAIQ, WOAOQ, WOBALT, WOBS, WOCCC, WOCDD, WOCMM, WOCO, WOCOCS, WOCOPN, WOCUEC, WOCYY, WODLCC, WODLSA, WODTCC, WODTCL, WODTCM, WODTLR, WODTOR, WODTST, WODUOM, WOGLCD, WOGNPN, WOIO, WOLINE, WOLOT, WOLSPD, WOLSPQ, WOLULN, WOMCDG, WOMCDR, WOMCEM, WOMCID, WOMCRD, WOMCTG, WOMCTR, WOMPDG, WOMPDR, WOMPEM, WOMPID, WOMPRD, WOMPSA, WOMPTG, WOMPTR, WOMSG, WOMVPT, WONOSP, WONOUT, WOODUE, WOOQTY, WOPLNR, WOPN, WOPOC, WOPPD, WOPPQ, WOPRJ, WOPRTD, WOPRTY, WOPRV, WOQTRC, WOQTSC, WOQTWH, WOQTY, WORALT, WOSCST, WOSLNO, WOSPLT, WOSTS, WOTBUR, WOTFXM, WOTLAB, WOTMAT, WOTMTL, WOTUS1, WOTUS2, WOTVAR, WOTVRM, WOTYPE, WOUDTE, WOUEVT, WOUNTM, WOUPGM, WOUTGT, WOUTIM, WOUUSR, WOWONO, WOWRKR, WOWTRS, WOYLD, WOYUOM
        // Target columns: WOACD, WOAIQ, WOAOQ, WOBALT, WOBS, WOCDATE, WOCO, WOCOCS, WOCOPN, WOCUEC, WODLDATE, WODTCLDT, WODTCMDT, WODTLRDT, WODTORDT, WODTSTDT, WODUOM, WOGLCD, WOGNPN, WOIO, WOLINE, WOLOT, WOLSPD, WOLSPQ, WOLULN, WOMCTGDATE, WOMCTRDATE, WOMCEM, WOMCID, WOMCRD, WOMPDGDATE, WOMPDRDATE, WOMPEM, WOMPID, WOMPRD, WOMPSA, WOMPTG, WOMPTR, WOMSG, WOMVPT, WONOSP, WONOUT, WOODUE, WOOQTY, WOPLNR, WOPN, WOPOC, WOPPD, WOPPQ, WOPRJ, WOPRTD, WOPRTY, WOPRV, WOQTRC, WOQTSC, WOQTWH, WOQTY, WORALT, WOSCST, WOSLNO, WOSPLT, WOSTS, WOTBUR, WOTFXM, WOTLAB, WOTMAT, WOTMTL, WOTUS1, WOTUS2, WOTVAR, WOTVRM, WOTYPE, WOUDATE, WOUEVT, WOUPGM, WOUTGT, WOUNTM, WOUUSR, WOWONO, WOWRKR, WOWTRS, WOYLD, WOYUOM

        Map<String, Object> modified_values = newValues;

        if (operation == MappingFunctionOperation.Delete) {
            modified_values.put("WOCDATE", null);
            modified_values.put("WODLDATE", null);
            modified_values.put("WODTCLDT", null);
            modified_values.put("WODTCMDT", null);
            modified_values.put("WODTLRDT", null);
            modified_values.put("WODTORDT", null);
            modified_values.put("WODTSTDT", null);
            modified_values.put("WOMCTGDATE", null);
            modified_values.put("WOMCTRDATE", null);
            modified_values.put("WOMPDGDATE", null);
            modified_values.put("WOMPDRDATE", null);
            modified_values.put("WOODUE", null);
            modified_values.put("WOUDATE", null);
            return new Pair<>(operation, modified_values);
        }

        try {
                modified_values.put("WOCDATE", makeDateTime(toBigDecimal(newValues.get("WOCMM")), toBigDecimal(newValues.get("WOCDD")), toBigDecimal(newValues.get("WOCYY")), toBigDecimal(newValues.get("WOCCC"))));
                modified_values.put("WODLDATE", makeDateTime("MMDDYY", toBigDecimal(newValues.get("WODLSA")), toBigDecimal(newValues.get("WODLCC"))));
                modified_values.put("WODTCLDT", makeDateTime("MMDDYY", toBigDecimal(newValues.get("WODTCL"))));
                modified_values.put("WODTCMDT", makeDateTime("MMDDYY", toBigDecimal(newValues.get("WODTCM"))));
                modified_values.put("WODTLRDT", makeDateTime("MMDDYY", toBigDecimal(newValues.get("WODTLR"))));
                modified_values.put("WODTORDT", makeDateTime("MMDDYY", toBigDecimal(newValues.get("WODTOR"))));
                modified_values.put("WODTSTDT", makeDateTime("MMDDYY", toBigDecimal(newValues.get("WODTST"))));
                modified_values.put("WOMCTGDATE", makeDateTime((LocalDate)makeDateTime("MMDDYY", toBigDecimal(newValues.get("WOMCDG"))), toBigDecimal(newValues.get("WOMCTG"))));
                modified_values.put("WOMCTRDATE", makeDateTime((LocalDate)makeDateTime("MMDDYY", toBigDecimal(newValues.get("WOMCDR"))), toBigDecimal(newValues.get("WOMCTR"))));
                modified_values.put("WOMPDGDATE", makeDateTime((LocalDate)makeDateTime("MMDDYY", toBigDecimal(newValues.get("WOMPDG"))), toBigDecimal(newValues.get("WOMPTG"))));
                modified_values.put("WOMPDRDATE", makeDateTime((LocalDate)makeDateTime("MMDDYY", toBigDecimal(newValues.get("WOMPDR"))), toBigDecimal(newValues.get("WOMPTR"))));
                modified_values.put("WOODUE", makeDateTime("MMDDYY", toBigDecimal(newValues.get("WOODUE"))));
                modified_values.put("WOUDATE", makeDateTime((LocalDate)makeDateTime("YYYYMMDD", toBigDecimal(newValues.get("WOUDTE"))), toBigDecimal(newValues.get("WOUTIM"))));
        } catch (Exception e) {
            throw new RuntimeException(e);
        }

        return new Pair<>(operation, modified_values);
    }

    /* ------------------------------------------------------------------
     * Helper functions ported from the DbMoto VB.NET scripting library.
     * Generated from the Gluesync UDF master template.
     * ------------------------------------------------------------------ */

    public static BigDecimal toBigDecimal(Object value) {
        if (value == null) {
            return null;
        }
        if (value instanceof BigDecimal) {
            return (BigDecimal) value;
        }
        return new BigDecimal(value.toString());
    }

    public static LocalDate toLocalDate(Object value) {
        if (value == null) {
            return null;
        }
        if (value instanceof LocalDate) {
            return (LocalDate) value;
        }
        if (value instanceof LocalDateTime) {
            return ((LocalDateTime) value).toLocalDate();
        }
        String s = value.toString().trim();
        if (s.isEmpty()) {
            return null;
        }
        if (s.length() >= 10) {
            return LocalDate.parse(s.substring(0, 10));
        }
        return LocalDate.parse(s);
    }

    public static LocalTime toLocalTime(Object value) {
        if (value == null) {
            return null;
        }
        if (value instanceof LocalTime) {
            return (LocalTime) value;
        }
        if (value instanceof LocalDateTime) {
            return ((LocalDateTime) value).toLocalTime();
        }
        String s = value.toString().trim();
        if (s.isEmpty()) {
            return null;
        }
        int tIdx = s.indexOf('T');
        if (tIdx >= 0) {
            s = s.substring(tIdx + 1);
        }
        if (s.length() > 8) {
            s = s.substring(0, 8);
        }
        return LocalTime.parse(s);
    }

    public static String toUpperString(Object value) {
        return value == null ? null : value.toString().toUpperCase();
    }

    public static String toLowerString(Object value) {
        return value == null ? null : value.toString().toLowerCase();
    }

    public static String trimString(Object value) {
        return value == null ? null : value.toString().trim();
    }

    /* DbMoto Int(x / y): integral part of the division */
    public static BigDecimal intDivide(BigDecimal value, BigDecimal divisor) {
        if (value == null || divisor == null) {
            return null;
        }
        return value.divideToIntegralValue(divisor);
    }

    /* DbMoto Int(x): truncates the decimal part */
    public static BigDecimal truncateToInt(BigDecimal value) {
        if (value == null) {
            return null;
        }
        return new BigDecimal(value.toBigInteger());
    }

    /* DbMoto LowDate(x): nulls out dates below the SQL Server low boundary */
    public static Object lowDate(Object value) {
        if (value == null) {
            return null;
        }
        LocalDate d = null;
        if (value instanceof LocalDateTime) {
            d = ((LocalDateTime) value).toLocalDate();
        } else if (value instanceof LocalDate) {
            d = (LocalDate) value;
        }
        if (d != null && d.compareTo(LocalDate.parse("1753-01-01")) < 0) {
            return null;
        }
        return value;
    }

    /* Decimal date in MMDDYY format -> DateTime */
    public static Object getDateMMDDYY(BigDecimal fullDate) throws Exception {
        if (fullDate == null) {
            return null;
        }
        int divDate = fullDate.abs().intValue();
        int day = (divDate % 10000) / 100;
        int month = divDate / 10000;
        int year = divDate % 100;
        if (year < 40) {
            year = 2000 + year;
        } else {
            year = 1900 + year;
        }
        return makeDateTime("YYYY", new BigDecimal(month), new BigDecimal(day), new BigDecimal(year));
    }

    /* Decimal date in CYYMMDD format -> DateTime */
    public static Object getDateCYYMMDD(BigDecimal fullDate) throws Exception {
        if (fullDate == null) {
            return null;
        }
        int divDate = fullDate.abs().intValue();
        int month = (divDate % 10000) / 100;
        int day = divDate % 100;
        int year;
        int century = divDate / 1000000;
        switch (century) {
            case 0:
                year = 1900 + (divDate / 10000);
                break;
            case 1:
                year = 2000 + ((divDate / 10000) - 100);
                break;
            default:
                return null;
        }
        return makeDateTime("YYYY", new BigDecimal(month), new BigDecimal(day), new BigDecimal(year));
    }

    /* Decimal date in YYMMDD format -> DateTime */
    public static Object getDateYYMMDD(BigDecimal fullDate) throws Exception {
        if (fullDate == null) {
            return null;
        }
        int divDate = fullDate.abs().intValue();
        int month = (divDate % 10000) / 100;
        int day = divDate % 100;
        int year = divDate / 10000;
        if (year < 40) {
            year = 2000 + year;
        } else {
            year = 1900 + year;
        }
        return makeDateTime("YYYY", new BigDecimal(month), new BigDecimal(day), new BigDecimal(year));
    }

    /* Decimal date in YYYYMMDD format -> DateTime */
    public static Object getDateYYYYMMDD(BigDecimal fullDate) throws Exception {
        if (fullDate == null) {
            return null;
        }
        int divDate = fullDate.abs().intValue();
        int month = (divDate % 10000) / 100;
        int day = divDate % 100;
        int year = divDate / 10000;
        return makeDateTime("YYYY", new BigDecimal(month), new BigDecimal(day), new BigDecimal(year));
    }

    /* MakeDateTime(formatYear, month, day, year) */
    public static Object makeDateTime(String formatYear, BigDecimal month, BigDecimal day, BigDecimal year) throws Exception {
        if (month == null || day == null || year == null) {
            return null;
        }
        int fullYear;
        int intMonth = month.intValue();
        int intDay = day.intValue();
        int intYear = year.intValue();

        if ("YY".equals(formatYear.toUpperCase())) {
            if (intYear <= 39) {
                fullYear = 2000 + intYear;
            } else {
                fullYear = 1900 + intYear;
            }
        } else if ("YYYY".equals(formatYear.toUpperCase())) {
            fullYear = intYear;
        } else {
            throw new Exception("Valid year formats are YY or YYYY");
        }

        if ((intMonth < 1) || (intMonth > 12)) {
            return null;
        }
        if ((intDay < 1) || (intDay > 31)) {
            return null;
        }
        if (fullYear < 1753) {
            return null;
        }
        if (((intMonth == 4) || (intMonth == 6) || (intMonth == 9) || (intMonth == 11)) && (intDay > 30)) {
            return null;
        } else if (intMonth == 2) {
            if ((fullYear % 4) == 0) {
                if (intDay > 29) {
                    return null;
                }
            } else {
                if (intDay > 28) {
                    return null;
                }
            }
        }
        return LocalDate.of(fullYear, intMonth, intDay);
    }

    /* MakeDateTime(month, day, shortYear, century) */
    public static Object makeDateTime(BigDecimal month, BigDecimal day, BigDecimal shortYear, BigDecimal century) throws Exception {
        if (month == null || day == null || shortYear == null || century == null) {
            return null;
        }
        BigDecimal fullYear;
        int intCentury = century.intValue();
        int intShortYear = shortYear.intValue();
        if (intCentury < 19) {
            fullYear = new BigDecimal(1900 + (100 * intCentury) + intShortYear);
        } else {
            fullYear = new BigDecimal((100 * intCentury) + intShortYear);
        }
        return makeDateTime("YYYY", month, day, fullYear);
    }

    /* MakeDateTime(formatDate, fullDate, century) */
    public static Object makeDateTime(String formatDate, BigDecimal fullDate, BigDecimal century) throws Exception {
        if (fullDate == null || century == null) {
            return null;
        }
        int divDate = fullDate.intValue();
        int day;
        int month;
        int year;
        int fullYear;
        int intCentury = century.intValue();

        if ("MMDDYY".equals(formatDate.toUpperCase())) {
            month = divDate / 10000;
            day = (divDate % 10000) / 100;
            year = divDate % 100;
        } else {
            throw new Exception("Valid format is MMDDYY");
        }

        if (intCentury < 19) {
            fullYear = 1900 + (100 * intCentury) + year;
        } else {
            fullYear = (100 * intCentury) + year;
        }
        return makeDateTime("YYYY", new BigDecimal(month), new BigDecimal(day), new BigDecimal(fullYear));
    }

    /* MakeDateTime(formatDate, fullDate) */
    public static Object makeDateTime(String formatDate, BigDecimal fullDate) throws Exception {
        if (fullDate == null) {
            return null;
        }
        switch (formatDate.toUpperCase()) {
            case "CYYMMDD":
                return getDateCYYMMDD(fullDate);
            case "MMDDYY":
                return getDateMMDDYY(fullDate);
            case "YYMMDD":
                return getDateYYMMDD(fullDate);
            case "YYYYMMDD":
                return getDateYYYYMMDD(fullDate);
            default:
                throw new Exception("Valid formats are CYYMMDD, MMDDYY, YYMMDD, and YYYYMMDD.");
        }
    }

    /* MakeDateTime(fullDate) - DATE passthrough with low-boundary validation */
    public static Object makeDateTime(LocalDate fullDate) {
        if (fullDate == null) {
            return fullDate;
        }
        if (fullDate.compareTo(LocalDate.parse("1753-01-01")) < 0) {
            return null;
        }
        return fullDate;
    }

    /* MakeDateTime(fullDate, fullTime) - DATE + TIME combination */
    public static Object makeDateTime(LocalDate fullDate, LocalTime fullTime) {
        if (fullDate == null) {
            return fullDate;
        }
        if (fullDate.compareTo(LocalDate.parse("1753-01-01")) < 0) {
            return null;
        }
        if (fullTime == null) {
            return fullDate;
        }
        return LocalDateTime.of(fullDate, fullTime);
    }

    /* MakeDateTime(fullDate, decimalTime) - DATE + decimal HHMMSS combination */
    public static Object makeDateTime(LocalDate fullDate, BigDecimal fullTime) {
        if (fullDate == null) {
            return fullDate;
        }
        if (fullDate.compareTo(LocalDate.parse("1753-01-01")) < 0) {
            return null;
        }
        if (fullTime == null) {
            return fullDate;
        }
        int tempTime = fullTime.abs().intValue();
        int hours = tempTime / 10000;
        int minutes = (tempTime % 10000) / 100;
        int seconds = tempTime % 100;
        if ((hours > 23) || (minutes > 59) || (seconds > 59)) {
            return fullDate;
        }
        return LocalDateTime.of(fullDate, LocalTime.of(hours, minutes, seconds));
    }

}
